### ISSUE TITLE
ESP32-WROOM-32 Initial Setup Problems

### ISSUE THREAD

**Issue by darethehair** [whitecatboard/Lua-RTOS-ESP32#398]
Fresh, out-of-the-bag ESP32:
```

darren@frodo3:~/Downloads$ ./wcc -d -p /dev/ttyUSB0 -f
2021/11/18 11:45:50 AppFolder:  /home/darren/Downloads
2021/11/18 11:45:50 AppFileName:  /home/darren/Downloads/wcc
2021/11/18 11:45:50 AppDataFolder:  /home/darren/.whitecat-create-agent
2021/11/18 11:45:50 AppDataTmpFolder:  /home/darren/.whitecat-create-agent/tmp
2021/11/18 11:45:50 connecting to board on /dev/ttyUSB0 ...
2021/11/18 11:45:50 attaching board ...
2021/11/18 11:45:51 start inspector ...
2021/11/18 11:45:51 waiting fot ready ...
2021/11/18 11:45:55 detaching board ...
Unknown board model.
Maybe your firmware is corrupted, or you haven't a valid Lua RTOS firmware installed.

Do you want to install a valid firmware now [y/n])? y

2021/11/18 11:46:13 detaching board ...
2021/11/18 11:46:13 closing serial port ...
panic: Get https://raw.githubusercontent.com/whitecatboard/Lua-RTOS-ESP32/master/boards/boards.json: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: read udp 192.168.100.60:36309->192.168.1.1:53: i/o timeout

goroutine 1 [running]:
panic(0x7e36e0, 0xc8204a02a0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.(*Board).selectSupportedBoard(0xc8200be210)
	/home/jaume/gows/src/github.com/whitecatboard/whitecat-console/board.go:1177 +0xbaf
main.main()
	/home/jaume/gows/src/github.com/whitecatboard/whitecat-console/main.go:314 +0x182c
```

Also tried a different chip, with the same results.  Help!

**Comment by the0ne** [comment]
Obviously the file https://raw.githubusercontent.com/whitecatboard/Lua-RTOS-ESP32/master/boards/boards.json cannot be downloaded. Make sure wcc has permission to download to that file.
